CREATE TABLE tb_trips (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip VARCHAR(255) NOT NULL,
    cost DECIMAL(19,2),
    person VARCHAR(255)
);

CREATE TABLE tb_registration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    age INT,
    email VARCHAR(255) UNIQUE,
    trips_id BIGINT,

    CONSTRAINT fk_registration_trip
    FOREIGN KEY (trips_id)
    REFERENCES tb_trips(id)
);